version: "3.9"
services:
  backend:
    build: https://github.com/ItzEarthy/KwikTrip_Tracker.git#main:backend
    ports:
      - 3001:3001
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped
  frontend:
    build: https://github.com/ItzEarthy/KwikTrip_Tracker.git#main:frontend
    ports:
      - 5173:80
    depends_on:
      - backend
    restart: unless-stopped