
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend/data.db:/app/data.db  # ✅ Mount single file persistently


  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"


volumes:
  sqlite-data:
